Fix(2 piscine-go exercise solutions)
01-edu/go-tests pull request #109
Opened 2022-08-05 10:53 UTC by MSilva95

Fix printStr solution upgrade
rotatevowels solution fix accordinf to dav review

2022-08-06 21:13 UTC, davhojt approved these changes
Let's not mix unrelated things into a single PR.

For example, if we were going to conduct a wholesale switch of integer literals to rune literals, then it would be reasonable to include many files in a single PR.

But changing `fmt.PrintLn` to `fmt.Print` doesn't appear related.

2022-08-06 21:48 UTC, davhojt requested changes
Sorry, I read it back to front before I approved before.

2022-08-06 21:48 UTC, davhojt commented on solutions/printstr.go
> +	fmt.Println(s)
The exercise this relates to should not be new-line terminated.

2022-08-08 08:36 UTC, MSilva95 commented on solutions/printstr.go
> +	fmt.Println(s)
Yes, but in my opinion we should have it with the new-line at the end, i added a change in the pr on public, but if you think we should not change it let me know and i will remove it.
<https://github.com/01-edu/public/pull/1378/files>

2022-08-10 00:09 UTC, rcatini commented on solutions/printstr.go
> +	fmt.Println(s)
@MSilva95 With the [upcoming new prompt](https://github.com/01-edu/public/pull/1357#discussion_r936788404) the example in the subject should become much clearer to understand (but I'm not sure when the new prompt will be introduced).

2022-08-10 08:39 UTC, MSilva95 commented on solutions/printstr.go
> +	fmt.Println(s)
yes but im not sure for when is the new prompt so i changed the exercise, but maybe i will let it stay like it was and i will speak with Dav to start implementing the new prompt

2022-08-10 15:12 UTC, davhojt commented
Exceptionally, I will merge this to master with a merge commit. The branch has been previously force-pushed so some references have changed.

2022-08-10 15:16 UTC, merged