Add write_a solutions ans tests
01-edu/go-tests pull request #110
Opened 2022-08-05 14:12 UTC by zainabdnaya

2022-11-03 14:39 UTC, tiagocollot requested changes

2022-11-03 14:39 UTC, tiagocollot commented on tests/returna_test/main.go
> +		{"Hello blah blah", "more blabh lah"},
When testing an array with multiple strings the program doesn't run, I would suggest to split the array that contains multiple strings into individual ones. When testing an array with only one string the program works correctly.

2022-11-03 14:52 UTC, tiagocollot approved these changes

2022-11-14 09:33 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-12-05 11:21 UTC, merged