DEV-3451-new-go-exercise-remove-duplicate
01-edu/go-tests pull request #119
Opened 2022-08-09 19:34 UTC by Hamzaelkhatri

2022-11-07 17:13 UTC, tiagocollot requested changes

2022-11-07 17:13 UTC, tiagocollot commented on tests/removeduplicate_test/main.go
> +		{1, 2, 3, 4, 5},
This condition doesn't make sense, since we are testing duplicates.

2022-11-07 17:13 UTC, tiagocollot commented on tests/removeduplicate_test/main.go
> +		{},
This condition doesn't make sense, since we are testing duplicates.

2022-11-07 17:13 UTC, tiagocollot commented on tests/removeduplicate_test/main.go
> +		{1},
This condition doesn't make sense, since we are testing duplicates.

2022-11-07 17:48 UTC, jotapero commented on tests/removeduplicate_test/main.go
> +		{1, 2, 3, 4, 5},
I think it can exist as an invalid output, to see behavior

2022-11-07 17:48 UTC, jotapero commented on tests/removeduplicate_test/main.go
> +		{},
I think it can exist as an invalid output, to see behavior

2022-11-07 17:49 UTC, jotapero commented on tests/removeduplicate_test/main.go
> +		{1},
I think it can exist as an invalid output, to see behavior

2022-11-09 15:33 UTC, tiagocollot approved these changes
LGTM! ⚡

2022-12-07 12:23 UTC, merged