Dev 3520 new go exercise loafofbread
01-edu/go-tests pull request #124
Opened 2022-08-24 19:38 UTC by tiagocollot

2022-08-25 15:55 UTC, eslopfer commented on solutions/loafofbread.go
> +	var _str strings.Builder
This doesn't mean it's wrong, I am just wondering, is there any reason for the leading underscore?

2022-08-29 10:56 UTC, tiagocollot commented on solutions/loafofbread.go
> +	var _str strings.Builder
A single leading underscore in front of a variable, a function, or a method name means that these objects are used internally, eventually used by a package or variable defined in another folder.

2022-08-29 12:42 UTC, eslopfer commented on solutions/loafofbread.go
> +	var _str strings.Builder
:+1:

2022-08-29 13:01 UTC, eslopfer requested changes

2022-08-29 13:01 UTC, eslopfer commented on solutions/loafofbread.go
> +	return (_str.String())
The solution for "This is a loaf of bread" doesn't match the description of the exercise.

2022-08-29 13:40 UTC, eslopfer requested changes

2022-08-29 13:40 UTC, eslopfer commented on tests/loafofbread_test/main.go
> +	table := []string{"Loaf of bread", "amazing loaf of bread", "bread crumbles", "", "bread slice", "bread"}
Add `"This is a loaf of bread"` to the test cases.
Also, this edge case triggered the thought of more edge cases that are not being tested and could make the exercise more challenging/interesting:
- space at the end of the sentence and it falls between words, when the last word reached 5
- space at the end of the sentence before the last word reaches 5
- space at the beginning of the sentence 
- double spaces
- several different amount of spaces between words
- sentences with only spaces

The solution should work for these as well.

2022-08-30 11:20 UTC, tiagocollot commented on solutions/loafofbread.go
> +	return (_str.String())
Fixed.

2022-08-30 11:20 UTC, tiagocollot commented on tests/loafofbread_test/main.go
> +	table := []string{"Loaf of bread", "amazing loaf of bread", "bread crumbles", "", "bread slice", "bread"}
This is a great suggestion! It is done

2022-09-01 15:04 UTC, eslopfer commented on solutions/loafofbread.go
> +	return (_str.String())
Thanks

2022-09-01 15:05 UTC, eslopfer commented on tests/loafofbread_test/main.go
> +	table := []string{"Loaf of bread", "amazing loaf of bread", "bread crumbles", "", "bread slice", "bread"}
Thanks

2022-09-05 16:29 UTC, merged