DEV-3504-feat(pisicine-go): add test new go exercise descendappendrange
01-edu/go-tests pull request #125
Opened 2022-08-29 15:24 UTC by tiagocollot

Created the test for the new go exercise descendappendrange .

2022-09-07 10:12 UTC, jotapero approved these changes
Everything in order!

2022-09-23 13:33 UTC, eslopfer requested changes

2022-09-23 13:33 UTC, eslopfer commented on solutions/descendappendrange.go
> +		for i := max ; i >= min + 1 ; i-- {
`i >= min + 1` is equivalent to `i > min`, but the second way requires less mental CPU cycles to understand, it's easier to read. Do you think it would make sense to change it?

2022-09-23 13:33 UTC, eslopfer commented on tests/descendappendrange_test/main.go
> +	args := []node{
Would it be a good idea to test for integer overflows as well?

2022-09-27 12:25 UTC, tiagocollot commented on tests/descendappendrange_test/main.go
> +	args := []node{
The goal of this exercise is not to be testing integer overflows.

2022-09-27 13:23 UTC, tiagocollot commented on solutions/descendappendrange.go
> +		for i := max ; i >= min + 1 ; i-- {
I think it makes total sense. Thank you for the correction. It is done.

2022-09-28 10:16 UTC, jotapero approved these changes
All good

2022-10-13 14:17 UTC, jotapero approved these changes

2022-10-18 09:26 UTC, merged