Dev 3517 new go exercise shoppinglistsort
01-edu/go-tests pull request #126
Opened 2022-08-31 10:22 UTC by tiagocollot

2022-09-07 11:24 UTC, jotapero approved these changes
Everything in order

2022-09-26 13:03 UTC, eslopfer requested changes

2022-09-26 13:03 UTC, eslopfer commented on solutions/shoppinglistsort.go
> +func ShoppingListSort(array[] string)[]string {
It shouldn't be called array.
Also please run gofmt.

2022-09-26 13:03 UTC, eslopfer commented on tests/shoppinglistsort_test/main.go
> +	array := [][]string{
Name and indentations are not correct.

2022-10-03 12:18 UTC, tiagocollot commented on solutions/shoppinglistsort.go
> +func ShoppingListSort(array[] string)[]string {
Name and indentation fixed!

2022-10-03 12:18 UTC, tiagocollot commented on solutions/shoppinglistsort.go
> +func ShoppingListSort(array[] string)[]string {
Argument name and indentation fixed!

2022-10-03 12:19 UTC, tiagocollot commented on tests/shoppinglistsort_test/main.go
> +	array := [][]string{
Variable name and indentation fixed!

2022-10-17 17:52 UTC, eslopfer commented
The comments have been addressed, but I can't approve until you implement a robust way to handle the order when length is the same. Right now if the length is the same, you expect the elements to be sorted in the same way as in your solution, but in the description you say that the order doesn't matter.

2022-10-24 08:27 UTC, eslopfer approved these changes

2022-10-24 13:03 UTC, merged