Dev 3505 new go exercise rocknroll
01-edu/go-tests pull request #127
Opened 2022-08-31 17:29 UTC by tiagocollot

Created and added test/solution.

2022-09-07 11:49 UTC, jotapero requested changes

2022-09-07 11:49 UTC, jotapero commented on solutions/rockandroll.go
> +	}
add two edge cases for negative numbers, and non divisible by 2 or 3:

```
} else if !(n < 0) || !((n%2 == 0) && (n%3 == 0)) {
		return "error: number is negative or non divisible "
	}

2022-09-08 11:25 UTC, jotapero approved these changes
seems to be an issue related to github's own indentation. On Tiago's machine the code is well indented

2022-09-26 10:52 UTC, eslopfer requested changes

2022-09-26 10:52 UTC, eslopfer commented on solutions/rockandroll.go
> +  } else if (n % 2 == 0) && !(n % 3 == 0) {
When opening the file in vs code the indentation is wrong, plus some other things, we don't need to run gofumpt, but at least gofmt. 
Also this is more like a suggestion/opinion, not a request to change, normally after a return you can avoid an else statement. 
```go
if ... {
    return ...
}
if ... {
    return ...
}
```
Else statements can add  unnecessary indentation and make the code harder to read.

2022-09-26 10:52 UTC, eslopfer commented on tests/rockandroll_test/main.go
> +	args := []int{20, 15, -125, 10, 5, 4, -9, 9, 24, 0, -85, 6, 11}
Do you think it would be a good idea to test for integer overflows?

2022-10-17 16:46 UTC, eslopfer requested changes
LGTM! :rocket:

2022-10-17 16:46 UTC, eslopfer commented on solutions/rockandroll.go
> +	if (n%2 == 0) && !(n%3 == 0) {
Since on the previous condition you are already checking for numbers divisible by 3, wouldn't the ` && !(n%3 == 0)` be redundant? all the numbers that are divisible by 2 will not be divisible by 3 or it would have returned on the previous if.

2022-10-17 16:46 UTC, eslopfer commented on solutions/rockandroll.go
> +	if (n%3 == 0) && !(n%2 == 0) {
Likewise as in the previous comment, the second part after `&&` is redundant.

2022-10-17 16:46 UTC, eslopfer commented on solutions/rockandroll.go
> +	if !(n < 0) || !((n%2 == 0) && (n%3 == 0)) {
This condition is not working. The first part if it's checking for negative numbers, should be without the `!`, and the second part I don't understand why it is there. If you test it with -2 it will print `rock`

2022-10-17 16:46 UTC, eslopfer commented on solutions/rockandroll.go
> +	return strconv.Itoa(n)
Why this return?

2022-10-24 08:18 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-24 12:56 UTC, merged