Dev 3514 new go exercise reversemenuindex
01-edu/go-tests pull request #128
Opened 2022-09-01 12:11 UTC by tiagocollot

Created and added the solution and test for the new go exercise reversemenuindex

2022-09-07 12:39 UTC, jotapero approved these changes
Everything in order

2022-09-08 11:52 UTC, jotapero approved these changes

2022-09-26 11:27 UTC, eslopfer requested changes

2022-09-26 11:27 UTC, eslopfer commented on tests/reversemenuindex_test/main.go
> +}
This curly brace is not indented, and so aren't the contents of the array. Please run gofmt to make sure this doesn't happen.

Also, it is not and array, it is a slice. The name is misleading.

2022-10-13 14:25 UTC, jotapero commented on tests/reversemenuindex_test/main.go
> +}
fixed

2022-10-17 20:09 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 09:31 UTC, merged