Dev 3516 new go exercise shoppingsummarycounter
01-edu/go-tests pull request #129
Opened 2022-09-01 18:26 UTC by tiagocollot

Created and added the solution/test for the new go exercise shoppingsummarycounter.

2022-09-07 15:40 UTC, jotapero requested changes

2022-09-07 15:40 UTC, jotapero commented on solutions/shoppingsummarycounter.go
> +    "fmt"
remove unused import "fmt"

2022-09-07 15:40 UTC, jotapero commented on tests/shoppingsummarycounter_test/main.go
> +	"github.com/01-edu/go-tests-training/solutions"
"github.com/01-edu/go-tests ~-training~ /solutions" remove strikeout

2022-09-08 11:55 UTC, tiagocollot commented on solutions/shoppingsummarycounter.go
> +    "fmt"
It is fixed!

2022-09-08 11:58 UTC, tiagocollot commented on tests/shoppingsummarycounter_test/main.go
> +	"github.com/01-edu/go-tests-training/solutions"
It is fixed!

2022-09-08 12:02 UTC, jotapero approved these changes

2022-09-26 12:33 UTC, eslopfer approved these changes
LGTM!

Please take a look at the suggestion in case you find it sensible.

2022-09-26 12:33 UTC, eslopfer commented on solutions/shoppingsummarycounter.go
> +        if ok {
This is a suggestion. To avoid the else  this could be rewritten this way: 
```go
if ok {
    counts[word] += 1
    continue
}
counts[word] = 1

2022-09-29 16:28 UTC, tiagocollot commented on solutions/shoppingsummarycounter.go
> +        if ok {
I'll leave this one as it is, but I'll consider this for the future practice.

2022-09-29 16:30 UTC, tiagocollot commented on solutions/shoppingsummarycounter.go
> +        if ok {
I'll leave this one as it is, but I'll have in consideration your suggestion for the future.

2022-10-17 19:46 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 10:21 UTC, merged