Dev 3502 new go exercise podiumposition
01-edu/go-tests pull request #130
Opened 2022-09-05 14:55 UTC by tiagocollot

Created and added the solution & test for new go exercise podiumposition.

2022-09-08 10:59 UTC, jotapero approved these changes
Everything in order

2022-09-23 13:02 UTC, eslopfer requested changes

2022-09-27 10:10 UTC, tiagocollot commented on solutions/podiumposition.go
> +func PodiumPosition(podium[][] string) [][]string {
It is fixed.

2022-09-28 10:13 UTC, jotapero approved these changes

2022-09-29 12:08 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 09:25 UTC, merged