DEV-3494-feat(piscine-go): add test/solution for new go exercise descendcomb
01-edu/go-tests pull request #131
Opened 2022-09-06 15:37 UTC by tiagocollot

Created and added  test/solution for new go exercise descendcomb

2022-09-08 11:22 UTC, jotapero requested changes

2022-09-08 11:22 UTC, jotapero commented on solutions/descendcomb.go
> +							break
indentation fix

2022-09-08 11:32 UTC, tiagocollot commented on solutions/descendcomb.go
> +							break
GitHub is no rendering correctly! The code in VsCode is just fine.

2022-09-08 11:33 UTC, jotapero approved these changes

2022-09-23 11:52 UTC, eslopfer requested changes

2022-09-23 11:52 UTC, eslopfer commented on solutions/descendcomb.go
> +            if i == 01 && j == 00 {
A number with a leading 0 is an octal. Although in this case it wouldn't affect the output, as octal 01 is 1 in decimal and likewise for 0, would you think it would maybe be better to make it decimal?

2022-09-23 12:36 UTC, eslopfer commented on solutions/descendcomb.go
> +							break
This is still not fixed

2022-09-26 16:31 UTC, tiagocollot commented on solutions/descendcomb.go
> +							break
It is fixed!

2022-09-26 16:35 UTC, tiagocollot commented on solutions/descendcomb.go
> +            if i == 01 && j == 00 {
You are very right regarding the octal numbers, but it would only affect the code if we were working with octals bigger than 7. So in this case I think there is no need to change the code to decimals (0x).

2022-09-28 10:07 UTC, jotapero commented on solutions/descendcomb.go
> +            if i == 01 && j == 00 {
I agree that the code should not have the octal notation, no need for it. Should be just 
```
if i == 1 && j == 0 
```

2022-09-28 10:40 UTC, tiagocollot commented on solutions/descendcomb.go
> +            if i == 01 && j == 00 {
The octal numbers are changed to decimal numbers. Done!

2022-09-28 10:50 UTC, jotapero approved these changes

2022-10-10 14:06 UTC, eslopfer commented on solutions/descendcomb.go
> +}
Please run gofmt, the indentation doesn't look right.

2022-10-10 14:59 UTC, tiagocollot commented on solutions/descendcomb.go
> +}
Thank you for noticing this. It is correctly indented.

2022-10-17 12:07 UTC, tiagocollot commented on solutions/descendcomb.go
> +}
It is done!

2022-10-17 13:35 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 09:20 UTC, merged