feat(piscine-go): add solution/test for new go exercise dealapackofcards
01-edu/go-tests pull request #132
Opened 2022-09-08 17:07 UTC by tiagocollot

Created and added solution and test for the new go exercise dealapackofcards

2022-09-23 11:01 UTC, jotapero approved these changes

2022-09-26 13:54 UTC, eslopfer requested changes

2022-09-26 13:54 UTC, eslopfer commented on solutions/dealapackofcards.go
> +		if (v == 1 && v < 3)  {
This condition doesn't make sense.

2022-09-26 13:54 UTC, eslopfer commented on solutions/dealapackofcards.go
> +		} else if (v == 3 && v < 6 ){
This condition doesn't make sense.

2022-09-26 13:54 UTC, eslopfer commented on solutions/dealapackofcards.go
> +		} else if (v == 9 && v <= 11){
This condition doesn't make sense.

2022-09-26 13:54 UTC, eslopfer commented on tests/dealapackofcards_test/main.go
> +									 {1, 2, 3, 4, 5, 17, 7  , 8, 9, 10   , 11 , 12},
This wrong indentation is on the source code, it's not a problem of how GitHub renders it.
Also, adding spaces to integers has no meaning.

2022-10-03 15:43 UTC, tiagocollot commented on solutions/dealapackofcards.go
> +		} else if (v == 3 && v < 6 ){
Thank for your observation. The code is refactored.

2022-10-03 15:44 UTC, tiagocollot commented on solutions/dealapackofcards.go
> +		} else if ( v == 6 && v < 9){
Thank for your observation. The code is refactored.

2022-10-03 15:44 UTC, tiagocollot commented on solutions/dealapackofcards.go
> +		} else if (v == 9 && v <= 11){
Thank for your observation. The code is refactored.

2022-10-03 15:57 UTC, tiagocollot commented on tests/dealapackofcards_test/main.go
> +									 {1, 2, 3, 4, 5, 17, 7  , 8, 9, 10   , 11 , 12},
The indentation is fixed,  and excess spaces removed.

2022-10-03 16:07 UTC, tiagocollot commented on solutions/dealapackofcards.go
> +		if (v == 1 && v < 3)  {
Thanks for your observation. The code is refactored.

2022-10-03 16:08 UTC, tiagocollot commented on tests/dealapackofcards_test/main.go
> +									 {1, 2, 3, 4, 5, 17, 7  , 8, 9, 10   , 11 , 12},
Also removed unnecessary edge cases!

2022-10-17 17:24 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 10:23 UTC, merged