feat(piscine-go): add solution for new go exercise stringtointarray
01-edu/go-tests pull request #133
Opened 2022-09-19 13:41 UTC by tiagocollot

Created and added the solution for the new go exercise stringtointarray.

2022-09-23 10:57 UTC, jotapero approved these changes
Everything looks good

2022-09-26 11:50 UTC, eslopfer requested changes

2022-09-26 11:50 UTC, eslopfer commented on solutions/stringtointarray.go
> +func StringToIntArray(str string) []int {
As mentioned in the readme review, the name is misleading, it is a slice not an array.

2022-09-26 11:50 UTC, eslopfer commented on tests/stringtointarray_test/main.go
> +		challenge.Function("StringToIntArray", student.StringToIntArray, solutions.StringToIntArray, s)
Same as above

2022-09-29 15:07 UTC, tiagocollot commented on solutions/stringtointarray.go
> +func StringToIntArray(str string) []int {
It is fixed.

2022-09-29 15:07 UTC, tiagocollot commented on tests/stringtointarray_test/main.go
> +		challenge.Function("StringToIntArray", student.StringToIntArray, solutions.StringToIntArray, s)
It is fixed.

2022-10-18 13:48 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 15:54 UTC, merged