feat(piscine-go): add solution/test for new go exercise fooddeliverytime
01-edu/go-tests pull request #134
Opened 2022-09-21 09:44 UTC by tiagocollot

Created and added the solution and test for the new go exercise fooddeliverytime.

2022-09-23 10:42 UTC, jotapero approved these changes
Everything looks good

2022-09-26 13:34 UTC, eslopfer requested changes

2022-09-26 13:34 UTC, eslopfer commented on solutions/fooddeliverytime.go
> +		return 404
There isn't any instruction in the description to return 404.

2022-09-26 13:34 UTC, eslopfer commented on solutions/fooddeliverytime.go
> +	} else if order == "chips" {
Please consider if you really want to use else statements after return.

2022-10-03 14:46 UTC, tiagocollot commented on solutions/fooddeliverytime.go
> +		return 404
Yes, it was missing the instruction in the exercise subject, it is fixed. Thank you for noticing that!

2022-10-03 14:51 UTC, tiagocollot commented on solutions/fooddeliverytime.go
> +	} else if order == "chips" {
I have been writing  the else if statement after return just to not lose the logic process when developing the code.
I'll take your advice into consideration and will implement it in the new exercises to come.

2022-10-17 20:01 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 10:22 UTC, merged