DEV-3189-feat(secondhalf): add test/solution for new go exam exercise
01-edu/go-tests pull request #136
Opened 2022-10-12 13:24 UTC by tiagocollot

Added test and solution for the exercise secondhalf in te Go Exam.

2022-11-03 15:31 UTC, jotapero requested changes

2022-11-03 15:31 UTC, jotapero commented on solutions/secondhalf.go
> +	if len(slice)%2 == 0 {
fix: `if size%2 == 0` - to make use of the variable otherwise is declared unnecessarily

2022-11-03 15:31 UTC, jotapero commented on solutions/secondhalf.go
> +		size = len(slice) / 2
fix: `size /= 2` - cleaner code and use of variable

2022-11-03 15:31 UTC, jotapero commented on solutions/secondhalf.go
> +		size = len(slice) / 2
fix: `size /= 2` - cleaner code and use of variable

2022-11-08 15:13 UTC, tiagocollot commented on solutions/secondhalf.go
> +		size = len(slice) / 2
It is fixed.

2022-11-08 15:13 UTC, tiagocollot commented on solutions/secondhalf.go
> +		size = len(slice) / 2
It is fixed.

2022-11-09 14:43 UTC, jotapero reviewed
LGTM :alien:

2022-11-09 14:43 UTC, jotapero approved these changes
LGTM :alien:

2022-11-14 08:07 UTC, eslopfer requested changes

2022-11-14 08:07 UTC, eslopfer commented on solutions/secondhalf.go
> +	} else {
What is the logic behind of having the two if/else branches doing the same thing? Also this solution is not rounding up when the length is odd.

2023-06-20 11:33 UTC, mikysett commented on solutions/secondhalf.go
> +	} else {
fixed both

2023-06-20 11:35 UTC, mikysett approved these changes
LGTM

2023-06-20 11:35 UTC, merged