DEV-3188-feat(halfslice): add test/solution for Go exam halfslice
01-edu/go-tests pull request #137
Opened 2022-10-12 15:34 UTC by tiagocollot

Added test and solution for Go exam halfslice

2022-11-03 15:13 UTC, jotapero requested changes

2022-11-03 15:13 UTC, jotapero commented on tests/halfslice_test/main.go
> +	"github.com/01-edu/go-tests-training/solutions"
Fix: "github.com/01-edu/go-tests/solutions"

2022-11-08 14:55 UTC, tiagocollot commented on tests/halfslice_test/main.go
> +	"github.com/01-edu/go-tests-training/solutions"
Thank you José for noticing it. It is fixed!

2022-11-09 14:42 UTC, jotapero approved these changes
LGTM :alien:

2022-11-14 07:59 UTC, eslopfer approved these changes
LGTM! :rocket:

2023-06-20 11:05 UTC, merged