DEV-3388-new-go-exercise-display-p
01-edu/go-tests pull request #143
Opened 2022-10-19 16:27 UTC by jotapero

PR was not created for this

2022-11-02 16:14 UTC, tiagocollot requested changes

2022-11-02 16:14 UTC, tiagocollot commented on solutions/onlyp/main.go
> +
The folder name doesn't match the exercise name. Needs to be changed.

2022-11-02 16:14 UTC, tiagocollot commented on solutions/onlyp/main.go
> +	z01.PrintRune('P')
The instruction of the exercise doesn't match the solution. The instruction says that the output must be followed by a newline, our solution doesn't match it. Or we don't add a newline and remove it from the subject, or we add it and we fix the solution.

2022-11-02 16:14 UTC, tiagocollot commented on tests/onlyp_test/main.go
> +
The folder name doesn't match the exercise name. Needs to be changed.

2022-11-02 16:14 UTC, tiagocollot commented on tests/onlyp_test/main.go
> +	challenge.Program("onlyP")
Instead of "challenge.Program("onlyP")" should be ---> challenge.Program("displayp"). Needs to be changed.

2022-11-03 12:17 UTC, tiagocollot requested changes

2022-11-03 12:17 UTC, tiagocollot commented on tests/onlyp_test/main.go
> +
We should increase the coverage of tests.

2022-11-09 14:29 UTC, tiagocollot approved these changes
LGTM!

2022-11-14 09:23 UTC, eslopfer requested changes

2022-11-14 09:23 UTC, eslopfer commented on solutions/displayp/main.go
> +package main
This file is no longer in the repo

2022-11-14 09:23 UTC, eslopfer commented on tests/displayp_test/main.go
> +package main
Likewise for this file

2022-12-05 17:18 UTC, merged