DEV-3386-new-go-exercise-only-b
01-edu/go-tests pull request #148
Opened 2022-10-20 10:48 UTC by jotapero

Created PR

2022-11-02 11:44 UTC, tiagocollot approved these changes

2022-11-03 12:10 UTC, tiagocollot requested changes

2022-11-03 12:10 UTC, tiagocollot commented on tests/onlyb_test/main.go
> +
I think we should increase the coverage os tests.

2022-11-07 14:28 UTC, jotapero commented on tests/onlyb_test/main.go
> +
Same answer as in onlyF exercise

2022-11-09 13:26 UTC, tiagocollot approved these changes
LGMT

2022-11-14 09:17 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-12-05 11:08 UTC, merged