DEV-3384-new go exercise is capitalaze fix
01-edu/go-tests pull request #149
Opened 2022-10-20 11:02 UTC by tiagocollot

Added the fixed test/solution for the new go exam exercise iscapitalized.

2022-11-03 17:21 UTC, jotapero requested changes

2022-11-03 17:21 UTC, jotapero commented on tests/iscapitalized_test/main.go
> +		" ",
Should this return `true`, are blank spaces considered non alphabetical characters? If so we should write it in the subject

2022-11-08 17:33 UTC, tiagocollot commented on tests/iscapitalized_test/main.go
> +		" ",
It is already explicit in the instruction.

2022-11-09 14:48 UTC, jotapero approved these changes
LGTM :alien:

2023-06-20 14:51 UTC, merged