DEV-3175-new-go-exercise-printfirsthalf-fix
01-edu/go-tests pull request #151
Opened 2022-10-20 13:00 UTC by tiagocollot

Added fixed test/solution.

2022-11-02 11:19 UTC, jotapero approved these changes
Looks good

2022-11-09 14:47 UTC, eslopfer requested changes

2022-11-09 14:47 UTC, eslopfer commented on solutions/printfirsthalf.go
> +		return "Invalid Output\n"
In the description of the exercise, it says that it should print, not return. Also the name of the function is Print. I can't review the rest because the way you choose to solve it might modify it.

2022-11-10 17:34 UTC, tiagocollot commented on solutions/printfirsthalf.go
> +		return "Invalid Output\n"
- The program is printing the output, as the instructions says. 
- "If the `string` is empty, return `Invalid Output` followed by a newline `\n`."  The student will return and not print  `Invalid Output` followed by a newline `\n`.
- "If the `string` length is equal to one, return the `string` followed by a newline `\n`." When the student is developing the code  he/she will return and not print the string, the program will print the string.

2022-11-14 06:42 UTC, eslopfer commented on solutions/printfirsthalf.go
> +		return "Invalid Output\n"
The name of the exercise starts by `print`, and also says to print on line 5 of the description but you are testing the value returned. Please make the instructions and the way you are going to check if the solution is correct coherent.

2023-06-16 16:24 UTC, mikysett commented
Removed ambiguity, now the subject is:
```
Write a function called `RetainFirstHalf()` that takes a `string` as an argument and returns the first half of this `string`.
```

2023-06-16 16:25 UTC, closed without merging