New exercice proposal to use maps in the piscine
01-edu/go-tests pull request #16
Opened 2021-07-30 17:02 UTC by Clemalfroy

Tested and written with @Frenchris

2021-08-02 15:52 UTC, xpetit requested changes
Good code, just reformat those files with `gofumpt` please

2021-08-02 15:52 UTC, xpetit commented on solutions/maxwordcountn.go
> +type KeyValue struct {
`KeyValue` and its members don't need to be exported

2021-08-02 15:52 UTC, xpetit commented on tests/maxwordcountn_test/main.go
> +type Args struct {
Doesn't need to be exported

2021-08-03 12:23 UTC, Clemalfroy commented on solutions/maxwordcountn.go
> +type KeyValue struct {
replaced by `keyValue`

2021-08-03 12:23 UTC, Clemalfroy commented on tests/maxwordcountn_test/main.go
> +type Args struct {
replaced by `functionArgs`

2021-08-09 07:42 UTC, xpetit approved these changes

2021-08-09 07:42 UTC, merged