DEV-4209 improvements-go-test
01-edu/go-tests pull request #164
Opened 2023-01-17 14:49 UTC by mikysett

This possible improvement was reported in this [PR from jesjos]( https://github.com/01-edu/go-tests/pull/20)

- Improve the readability on how the errors (mainly I/O) are handled or discarded by explicitly take the results of I/O functions.
- Better names for some variables used by tests.

Thanks a lot to jesjos for the contribution.

2023-02-08 15:23 UTC, MSilva95 requested changes
The quad_test part is already like that on master, so i think it can be removed,  the rest looks good to me

2023-02-08 15:23 UTC, MSilva95 commented on tests/quad_test/main.go
> +			challenge.Function("quadA", student.QuadA, quadA, table[i], table[i+1])
I think this is already done on master

2023-02-08 15:43 UTC, mikysett commented on tests/quad_test/main.go
> +			challenge.Function("quadA", student.QuadA, quadA, table[i], table[i+1])
Yes the change is already present on master but this branch was created before master was changed, this is why the diff shows differences there.

I think we can just ignore that one and merge, since there is no way for me to "remove" this diff and it won't actually have any effect on the merge anyway.

PS: I could try to rebase from master but I think it's not necessary and it could create a too complicated git history for no real advantage, what do you think?

2023-02-10 15:56 UTC, MSilva95 approved these changes
LGTM!

2023-02-10 15:56 UTC, MSilva95 commented on tests/quad_test/main.go
> +			challenge.Function("quadA", student.QuadA, quadA, table[i], table[i+1])
Lets not complicate, i don't think it will do anything wrong so lets merge

2023-02-15 12:54 UTC, merged