quad test
01-edu/go-tests pull request #17
Opened 2022-02-01 10:14 UTC by MSilva95

2022-03-03 10:12 UTC, LEEDASILVA commented on tests/quadchecker_test/main.go
> +			}
If the test fail the binary files still continue to exist.
Maybe we can do something like in the challenge, create `tmp` files for the binaries (just the solution at least and remove / update the students one)

2022-03-03 10:24 UTC, LEEDASILVA commented on tests/sudoku_test/main.go
> +	err := os.Remove(path)
this is returning an error `remove /tmp/binaries/student/sudoku: no such file or directory`
Maybe you will have to make a condition checking if the file exists.

2022-03-03 10:38 UTC, LEEDASILVA commented on tests/quad_test/main.go
> +	)
i remember that Xav left some TODO messages on the challenge 

https://github.com/01-edu/go-tests/blob/d53f02a9e84c7db23c3aa8b6131ad9abdc970708/lib/challenge/challenge.go#L189

https://github.com/01-edu/go-tests/blob/d53f02a9e84c7db23c3aa8b6131ad9abdc970708/lib/challenge/challenge.go#L190

not sure if it applies to those random cases

2022-03-03 11:12 UTC, LEEDASILVA commented on tests/sudoku_test/main.go
> +	err := os.Remove(path)
this was the command i used to run the tests `go run github.com/01-edu/go-tests/tests/sudoku_test`

2022-03-04 09:53 UTC, MSilva95 commented on tests/sudoku_test/main.go
> +	err := os.Remove(path)
Its working now

2022-03-04 09:54 UTC, MSilva95 commented on tests/quadchecker_test/main.go
> +			}
the test now deletes the binary file even when it fails a test

2022-03-04 10:06 UTC, LEEDASILVA requested changes

2022-03-04 10:06 UTC, LEEDASILVA commented on tests/sudoku_test/main.go
> +		return
if the program fails then it will not remove the binary file because it failed and does not execute the `os.Remove`.

2022-03-04 10:06 UTC, LEEDASILVA commented on tests/sudoku_test/main.go
> +		return
instead of using `fmt.Println` you can import from the challenge the function `Fatal` and no need to return

2022-03-04 10:08 UTC, LEEDASILVA commented on tests/sudoku_test/main.go
> +		return
you can do it like this `challenge.Fatal(err)`, don't know

2022-03-04 10:18 UTC, LEEDASILVA commented
if there is a problem with the binaries that are being saved on the`tmp` files. This probably will happen to every exercise that is a program ? which means it should be changed on the challenge level ? 

i tested with the exercise `cat` & `ztail` and it is giving me the same error. (the cached binary is not being updated, for the student)

Maybe we should talk about it @Frenchris and @MSilva95 ?

2022-03-08 14:38 UTC, LEEDASILVA approved these changes
So the changes look good now.

Still would like to discuss about the exercises that are programs. Since they are not working has well. Maybe we could talk about it

2022-03-28 15:42 UTC, LEEDASILVA approved these changes
I see that the sudoku contains the the clean up of the students `tmp` file, so this way the admin tests without the need of always removing the students solution. LGTM

2022-03-30 11:12 UTC, kigiri reviewed
I think we should include an edit of the readme to make the instruction useful to someone outside of the platform

2022-04-06 08:40 UTC, merged