CON-1672-add-scirpt-to-test-exercises-in-docker-container-for-go-tests
01-edu/go-tests pull request #170
Opened 2023-06-30 16:41 UTC by mikysett

Should speed-up the testing process
requires valid solutions in `piscine-go` next to `go-tests`

2023-07-04 15:46 UTC, nprimo commented on README.md
> +For convenience to do bulk tests you may want to store those info in a `meta.txt` file that will separate them with `:` and then use `awk` to run tests on all of them.
it should be 
```
... this info ...
```

2023-07-04 15:50 UTC, nprimo commented on README.md
> +./test_with_docker.sh [EXERCISE_NAME] [EXERCISE_PATH] [ALLOWED_FUNCTION]*
You need to have locally the `go-test` image build with the command in the github action in this repo (`.github/workflows/ga-image-build-master.yml`) or have the `runner` up with the permission to pull the proper Docker Image to run this command - it might be handy to add this information. 

The easiest is to be sure to have an updated local Docker image by running the command found in the github action.
```
docker build . --file Dockerfile --tag ghcr.io/01-edu/test-go:latest
```

2023-07-04 15:55 UTC, nprimo commented on test_with_docker.sh
> +			-t go_tests
I would use the same name as the github action (`ghcr.io/01-edu/test-go:latest`) or add a `docker build -t go_tests .` in the script

2023-07-04 15:59 UTC, nprimo commented on test_with_docker.sh
> +
Not required, but if might be nice to add a simple arg count check like 

```bash
if [[ "$#" -lt  3 ]]; then
    echo "Error: run with ./test_with_docker.sh EXERCISE_NAME EXERCISE_FILE ALLOWED_FUNCTIONS"
    echo "ALLOWED_FUNCTIONS is optional"
    exit 1
fi
```

```

2023-07-04 16:08 UTC, nprimo commented on test_with_docker.sh
> +			--volume "$(pwd)"/../piscine-go:/jail/student:ro \
Why not use the solutions in this repo instead of `piscine-go`?

2023-07-04 16:09 UTC, nprimo requested changes
I left some comments inline. I am available to talk via Discord to clarify some points if needed :)

2023-07-04 16:20 UTC, mikysett commented on README.md
> +For convenience to do bulk tests you may want to store those info in a `meta.txt` file that will separate them with `:` and then use `awk` to run tests on all of them.
done

2023-07-04 16:26 UTC, mikysett commented on test_with_docker.sh
> +
nice, I've added it

2023-07-04 16:29 UTC, mikysett commented on test_with_docker.sh
> +			--volume "$(pwd)"/../piscine-go:/jail/student:ro \
Because `solutions` are used as golden tests (they also have different imports, not sure it will work).

Even if it works it will means that a test will evaluate `solutions` output against the very same `solutions`, which makes it impossible to test failing solutions defeating the very purpose of testing.

2023-07-04 16:30 UTC, mikysett commented on test_with_docker.sh
> +			-t go_tests
nice point, I've added a line for building in the readme

2023-07-04 16:31 UTC, mikysett commented on README.md
> +./test_with_docker.sh [EXERCISE_NAME] [EXERCISE_PATH] [ALLOWED_FUNCTION]*
yes I forgot about that step, I've added it.

2023-07-04 17:01 UTC, nprimo commented on test_with_docker.sh
> +			--volume "$(pwd)"/../piscine-go:/jail/student:ro \
Ok, thank you for the clarification :)

2023-07-05 08:39 UTC, nprimo approved these changes
LGTM :rocket:

2023-07-05 09:12 UTC, merged