CON-2639 exercise findspairs
01-edu/go-tests pull request #182
Opened 2024-04-22 14:07 UTC by MSilva95

CON-2639

exercise findspairs test and sol

2024-04-22 15:30 UTC, nprimo requested changes
I have left some comments with the diff that I feel should be applied to make the test vs an expected result using a "custom" function (`runStudentProgram`) instead of running our solution vs the student one. If the print should have a new line we should update all the `want` testCases to have `\n` at the end :)

There were some "weird" test cases as well.

2024-04-22 15:50 UTC, MSilva95 commented on tests/findpairs_test/main.go
Used the other version so it would be faster to create, but updated to this one it works as expected thanks

2024-04-22 15:50 UTC, MSilva95 commented on solutions/findpairs/main.go
fixed, i forgot to save before the push, so the tests were messy sorry my bad.

2024-05-02 15:03 UTC, nprimo requested changes
The current tests are not passing with the provided solution - I have added some possible solutions in the comments :)

2024-05-02 15:03 UTC, nprimo commented on solutions/findpairs/main.go
The first block is to allow the "Invalid number: ..." error - if not errors will always be `"Invalid input."`.
The second one is just a small formatting issues, to avoid extra spaces to fail :)

2024-05-02 15:03 UTC, nprimo commented on tests/findpairs_test/main.go
>  	for _, tc := range tests {
Nothing special, but I would add the following formatting to the error message when a test fails to give more context:
```diff
diff --git a/tests/findpairs_test/main.go b/tests/findpairs_test/main.go
index 2d28c0d..03c8f75 100644
--- a/tests/findpairs_test/main.go
+++ b/tests/findpairs_test/main.go
@@ -73,7 +73,8 @@ func main() {
        for _, tc := range tests {
                got, _ := runStudentProgram("findpairs", []string{tc.arr, tc.targetSum}...)
                if got != tc.want {
-                       fmt.Printf("\ngot: %+v\nwant: %+v\n", got, tc.want)
+                       fmt.Printf("findpairs %q %q -> ", tc.arr, tc.targetSum)
+                       fmt.Printf("got: %q instead of %q\n", got, tc.want)
                        os.Exit(1)
                }
        }
```

2024-05-02 15:33 UTC, MSilva95 commented on tests/findpairs_test/main.go
>  	for _, tc := range tests {
Done, thanks

2024-05-02 15:33 UTC, MSilva95 commented on solutions/findpairs/main.go
there was also other test not passing but its fixed now, thanks

2024-05-02 15:52 UTC, nprimo requested changes

2024-05-02 15:52 UTC, nprimo commented on solutions/findpairs/main.go
> +	s = s[1 : len(s)-1]
This check is done after at line 57 - I will remove everything till line 35
(current line numbers)

2024-05-02 15:52 UTC, nprimo commented on solutions/findpairs/main.go
> +	for _, strNum := range strNums {
```diff
@@ -55,9 +45,10 @@ func main() {
        strNums := strings.Split(arrayStr, ",")
        var arr []int
        for _, strNum := range strNums {
-               num, err := strconv.Atoi(strings.TrimSpace(strNum))
+               s := strings.TrimSpace(strNum)
+               num, err := strconv.Atoi(s)
                if err != nil {
-                       fmt.Printf("Invalid number: %s\n", strNum)
+                       fmt.Printf("Invalid number: %s\n", s)
                        return
                }
                arr = append(arr, num)
```

I would change this chunk as above to avoid space issues - if the string as several spaces, For example:
- with this test case
```go
		{
			arr:       "[1, 2, 3, 4, 20,    p, 5]",
			targetSum: "5",
			want:      "Invalid number: p\n",
		},

```
I get:
```console
findpairs "[1, 2, 3, 4, 20,    p, 5]" "5" -> got: "Invalid number:    p\n" instead of "Invalid number: p\n"
exit status 1
```

2024-05-06 16:28 UTC, MSilva95 commented on solutions/findpairs/main.go
> +	s = s[1 : len(s)-1]
done

2024-05-06 16:28 UTC, MSilva95 commented on solutions/findpairs/main.go
> +	for _, strNum := range strNums {
Done, thanks

2024-05-07 08:56 UTC, nprimo requested changes
There is just a small formatting difference between the current solution and the expected one from the tests :)
I left a comment inline

2024-05-07 08:56 UTC, nprimo commented on solutions/findpairs/main.go
> +			fmt.Printf("Invalid number:%s\n", s)
there is a missing space here

2024-05-08 17:02 UTC, MSilva95 commented on solutions/findpairs/main.go
> +			fmt.Printf("Invalid number:%s\n", s)
done

2024-05-09 12:06 UTC, nprimo approved these changes
LGTM :rocket:

2024-05-10 08:54 UTC, merged