CON-2642 canjump solution and test
01-edu/go-tests pull request #183
Opened 2024-04-22 17:50 UTC by MSilva95

CON-2642 

 canjump solution and test

2024-04-23 19:03 UTC, nprimo requested changes

2024-04-23 19:03 UTC, nprimo commented on solutions/canjump.go
> +func CanJump(steps ...int) bool {
A possible implementation to solve what  got from the subject:
```go
func CanJump(in []uint) bool {
	if len(in) == 0 {
		return false
	}
        if len(in) == 1 {
           return true
        }

	toReach := len(in) - 1
	var maxReached uint
	for i := uint(0); i <= uint(toReach); i++ {
		if maxReached < i {
			return false
		}
		for j := in[i]; j > 0; j-- {
			maxReached = max(maxReached, j+i)
			if maxReached >= uint(toReach) {
				return true
			}
		}
	}

	return false
}
```

2024-05-06 17:29 UTC, MSilva95 commented on solutions/canjump.go
> +func CanJump(steps ...int) bool {
my bad this was the first version, now its a uint as suggested

2024-05-07 08:43 UTC, nprimo commented on tests/canjump_test/main.go
> +		{args: []int{1, 2, 3, 0, 2}, want: false},
The issue (for what I understand in the subject) is that the number represent "the maximum number of steps" and not "the precise number of steps", therefore I still don't think this test and the below ones should be `false`.

2024-05-07 08:44 UTC, nprimo commented on tests/canjump_test/main.go
> +func uintSliceToString(nums []uint) string {
This function can be removed in my opinion - the `$#v` format the array with hexadecimal notation (`0x01`,...), but the `$+v` format it in a more "human friendly" way :)

2024-05-08 17:00 UTC, MSilva95 commented on tests/canjump_test/main.go
> +func uintSliceToString(nums []uint) string {
done

2024-05-09 12:07 UTC, nprimo approved these changes
LGTM

2024-05-10 08:54 UTC, merged