CON-2661 [CHECKPOINT-RESTRUCTURE] Make `gcd` solution a function instead of a program
01-edu/go-tests pull request #184
Opened 2024-04-29 12:57 UTC by nprimo

- update tests accordingly

2024-06-05 17:02 UTC, MSilva95 requested changes
The test is not responding when we give wrong solutions

2024-06-06 09:43 UTC, nprimo commented on tests/gcd_test/main.go
>  package main
I got a timeout when testing with this solution:

```console
timeout: Did you write an infinite loop? context deadline exceeded%
```

2024-06-12 16:14 UTC, MSilva95 approved these changes
LGTM!

2024-06-27 21:40 UTC, HarryVasanth approved these changes
> [!NOTE]
>  ✅ Production and pre-production prerequisites have been deployed.
> #### Clear to merge!

2024-06-27 21:41 UTC, merged