fix: inconsistencies and errors
01-edu/go-tests pull request #2
Opened 2021-06-07 17:22 UTC by LEEDASILVA

`trimatoi_test` :
- the solution was incorrect, some times it passed and sometimes it did not
- added extra cases to test (for the test cases that did not pass)

`pointone_test`:
- function `PointOne` was not being used

2021-06-08 19:11 UTC, xpetit requested changes

2021-06-08 19:11 UTC, xpetit commented on solutions/trimatoi.go
> +func recursion(s string, i int) string {
I don't like recursion, especially to filter a string. Two other ways:
```go
s = strings.Map(func(r rune) rune {
	if (r < '0' || r > '9') && r != '-' {
		return -1
	}
	return r
}, s)
```
```go
var s2 string
for _, r := range s {
	if (r >= '0' && r <= '9') || r == '-' {
		s2 += string(r)
	}
}
```

2021-06-08 19:11 UTC, xpetit commented on solutions/trimatoi.go
> +	if a, err := strconv.Atoi(recursion(s, len(s)-1)); err == nil {
if `strconv.Atoi` fails it returns `0` by default, so you can confidently return the first value and ignore the second (the error)

2021-06-09 08:23 UTC, LEEDASILVA commented on solutions/trimatoi.go
> +func recursion(s string, i int) string {
the solutions looks good but the it does not pass a special case int the tests `"sdx1-fa2W3s4"` for example.
so will add `if (r >= '0' && r <= '9') || (r == '-' && s2 == "")`

2021-06-09 08:24 UTC, LEEDASILVA commented on solutions/trimatoi.go
> +	if a, err := strconv.Atoi(recursion(s, len(s)-1)); err == nil {
nice

2021-06-09 10:02 UTC, xpetit approved these changes

2021-06-09 10:02 UTC, merged