Feature/improve tests
01-edu/go-tests pull request #20
Opened 2022-05-17 12:12 UTC by jesjos

1. the `Function` testing utility makes some hidden assumptions about which input is the expected and which is the function under test. Make this explicit.
2. Explicitly ignore errors in order to appease linters
3. Flip calls to `Function` in `quad_test` to reflect usage.

2022-06-06 07:55 UTC, jesjos commented
Are there any maintainers available to look at PRs? E.g. @kigiri ?

2023-01-16 15:46 UTC, MSilva95 requested changes
If you would like to change only the names of the functions, please fix the pr accordingly.
Thank you for the feedback!

2023-01-16 15:46 UTC, MSilva95 commented on lib/challenge/challenge.go
> +		_, _ = io.Copy(&buf, r)
just by adding the `_,_` doesn't take care of the error handling
But, we will take this into consideration and check for the best way to fix it.

2023-01-16 15:46 UTC, MSilva95 commented on tests/quad_test/main.go
> +			challenge.Function("quadA", student.QuadA, quadA, table[i], table[i+1])
this is already fixed here, you need to update your master
<https://github.com/01-edu/go-tests/pull/21/files>

2023-01-17 06:51 UTC, jesjos commented on lib/challenge/challenge.go
> +		_, _ = io.Copy(&buf, r)
I'm not trying to "fix " error handling, I'm making it explicit that the original author chose not to do any error handling.

2023-01-17 14:52 UTC, mikysett commented
@jesjos thanks a lot for your contribution, this PR will be merged [on this one](https://github.com/01-edu/go-tests/pull/164) since we made some little adjustments on variable names.

2023-01-17 14:52 UTC, closed without merging