add Zipstring exercise tests and solution
01-edu/go-tests pull request #22
Opened 2022-06-08 09:54 UTC by mohamedLazyBob

2022-06-20 22:01 UTC, Hamzaelkhatri requested changes

2022-06-20 22:01 UTC, Hamzaelkhatri commented on tests/zipstring_test/main.go
> +func getResult(input string) string {
use `solution.Zipstring` instead of this funciton

2022-06-20 22:01 UTC, Hamzaelkhatri commented on tests/zipstring_test/main.go
> +		challenge.Function("AlphaCount", student.ZipString, getResult, arg)
change name of function

2022-08-04 09:12 UTC, MSilva95 requested changes
How is this here if it doesn't even test the right function?
You didn't reply the comments that @Hamzaelkhatri did and you didn't fix the problems he found...

2022-11-09 11:44 UTC, closed without merging