add(test) : frontback test and solution
01-edu/go-tests pull request #23
Opened 2022-06-08 15:48 UTC by Hamzaelkhatri

2022-06-13 16:19 UTC, mohamedLazyBob approved these changes

2022-07-18 17:19 UTC, MSilva95 requested changes

2022-07-18 17:19 UTC, MSilva95 commented on tests/frontback_test/main.go
> +		challenge.Program("frontback", strings.Fields(s)...)
this is not testing, make the name of the folder in public and go-tests the same, and fix the naming in the func call as well accordingly

2022-07-19 18:18 UTC, Hamzaelkhatri commented on tests/frontback_test/main.go
> +	table := []string{
added

2022-07-19 18:20 UTC, Hamzaelkhatri commented on tests/frontback_test/main.go
> +		challenge.Program("frontback", strings.Fields(s)...)
I change the name of the folder on the solution side, I guess the name is the same for the other part (subject & test)

2022-07-22 13:43 UTC, MSilva95 approved these changes

2022-11-10 16:47 UTC, tiagocollot approved these changes
LGTM! ⚡

2022-12-05 12:15 UTC, merged