feat(issamestring): solution and testing program
01-edu/go-tests pull request #28
Opened 2022-06-09 21:57 UTC by mohamedLazyBob

resolves 01-edu/public#1157

2022-06-17 17:43 UTC, zainabdnaya reviewed
Code works well!

2022-06-17 17:43 UTC, zainabdnaya commented on tests/issamestring_test/main.go
> +		{`abcdefgh`, `abcdefghijklmnopqrstuvwxyz`},
Well done , just try to add test that include space and tabulation

2022-11-09 12:13 UTC, jotapero approved these changes
Looks Good :alien:

2022-11-09 16:18 UTC, tiagocollot requested changes

2022-11-09 16:18 UTC, tiagocollot commented on solutions/issamestring.go
> +	"unicode"
Remove unnecessary "( )" from import.

2022-11-10 13:18 UTC, jotapero commented on solutions/issamestring.go
> +	"unicode"
fixed

2022-12-05 12:24 UTC, merged