Add Solution & Test: Rect Perimeter exam function
01-edu/go-tests pull request #29
Opened 2022-06-10 08:09 UTC by mohamedLazyBob

resolves 01-edu/public#1149

2022-06-10 11:14 UTC, Hamzaelkhatri approved these changes
all is good 💯

2022-06-10 13:58 UTC, zainabdnaya reviewed
Well Done

2022-06-13 12:33 UTC, zainabdnaya reviewed
All Good

2022-06-20 23:20 UTC, davidrobert99 requested changes

2022-06-20 23:20 UTC, davidrobert99 commented on tests/rectperimeter_test/main.go
> +		{14342, -1},
Consider adding a test case with a negative value on the left and a positive value on the right. If the student only forgets to verify if w < 0 the test will pass and it should not.

2022-11-09 11:25 UTC, jotapero approved these changes
Looks Good :alien:

2022-11-09 16:54 UTC, tiagocollot requested changes

2022-11-10 13:57 UTC, jotapero commented on tests/rectperimeter_test/main.go
> +
fixed

2022-11-10 17:56 UTC, tiagocollot approved these changes
LGTM ⚡

2022-12-05 12:23 UTC, merged