clarification : adding function name to parameter value
01-edu/go-tests pull request #3
Opened 2021-06-08 17:32 UTC by LEEDASILVA

`challenge.go`: added function name to parameter value for clarification reason.

passed form this : 

```console
Map((func(int) bool)(0x4b72c0), []int{-967443, 619198, 463968, 143759, -982455, -583859, -661349, 610921}) == []bool{false, true, true, true, true, true, true, true} instead of []bool{false, true, true, true, false, false, false, true}
exit status 1
```

to

```console
Map(github.com/01-edu/go-tests/lib/is.Prime, []int{-944272, -826596, -612484, -646566, 771985, -978566, 761982, -398507}) == []bool{false, false, true, true, false, true, false, true} instead of []bool{false, false, false, false, false, false, false, false}
exit status 1
```

`advancedsortwordarr_test/main.go`: added function name for clarification reason.

2021-06-08 19:43 UTC, xpetit requested changes
Naisu

2021-06-08 19:43 UTC, xpetit commented on lib/challenge/challenge.go
> +			if function := fmt.Sprint(reflect.TypeOf(v)); strings.Contains(function, "func") {
It might be better to do a direct comparison instead of parsing the "pretty print" :
```go
reflect.TypeOf(v).Kind() == reflect.Func
```

2021-06-08 19:43 UTC, xpetit commented on lib/challenge/challenge.go
> +				// function: function passed as parameter should output the name of the function
`function: function passed [...] name of the function`
=>
`Function passed [...] its name`

2021-06-09 07:59 UTC, LEEDASILVA commented on lib/challenge/challenge.go
> +			if function := fmt.Sprint(reflect.TypeOf(v)); strings.Contains(function, "func") {
nice

2021-06-09 08:03 UTC, xpetit approved these changes

2021-06-09 08:04 UTC, merged