add(Test): add solution and test for rev args
01-edu/go-tests pull request #35
Opened 2022-06-13 09:30 UTC by Hamzaelkhatri

2022-06-13 12:46 UTC, zainabdnaya reviewed
Tested
 it's all good

2022-06-22 11:18 UTC, davidrobert99 requested changes

2022-06-28 09:18 UTC, MSilva95 commented on tests/revargs_test/main.go
> +	}
use some random cases to prevent cheating something like this:
```
	for i := 0; i < 5; i++ {
		rand := []string{random.Str(chars.Words, 13), random.Str(chars.Words, 6)}
		fmt.Println(rand)
		args = append(args, rand)
	}

2022-07-08 11:28 UTC, MSilva95 approved these changes

2022-07-14 07:30 UTC, merged