add(test): leap-Year
01-edu/go-tests pull request #37
Opened 2022-06-13 11:10 UTC by Hamzaelkhatri

2022-06-13 11:24 UTC, zainabdnaya reviewed
All  well done

2022-06-21 01:54 UTC, davidrobert99 requested changes

2022-06-21 01:54 UTC, davidrobert99 commented on solutions/leapyear.go
> +	if year%4 == 0 {
It should be verified if the number is negative or not (-2012 returns true).

2022-06-21 01:54 UTC, davidrobert99 commented on tests/leapyear_test/main.go
> +		-10,
It must be added at least a negative leap year to the test cases (like -2012)

2022-06-21 21:02 UTC, davidrobert99 requested changes

2022-06-21 21:02 UTC, davidrobert99 commented on solutions/leapyear.go
> +	}
It should be <= 0 because the year 0 is not considered a year, so it should return false.

2022-06-21 21:02 UTC, davidrobert99 commented on tests/leapyear_test/main.go
> +		-10,
Probably consider adding the value 0 to the test.

2022-06-21 23:25 UTC, davidrobert99 approved these changes

2022-06-22 08:26 UTC, zainabdnaya approved these changes

2022-06-22 15:19 UTC, merged