refactor linklist exercises
01-edu/go-tests pull request #4
Opened 2021-06-11 10:43 UTC by LEEDASILVA

refactor linked list exercises, tested both in platform and locally

2021-06-11 16:31 UTC, xpetit requested changes
four hundred less lines, that's awesome

2021-06-11 16:31 UTC, xpetit commented on solutions/listforeachif.go
> +func IsAl_node(node *NodeL) bool {
Function name is not idiomatic. Even if I prefer snake case to camel case, we have to respect Go conventions, so no `_` in identifiers

2021-06-11 16:31 UTC, xpetit commented on solutions/listforeachif.go
> +		return true
```go
case string, rune:
	return true
}
return true
```
=>
```go
default:
	return true
}
```

2021-06-11 16:31 UTC, xpetit commented on tests/listfind_test/main.go
> +		if len(arg.Data) != 0 {
This purely stylish and personal taste: I prefer `len() > 0` to `len() != 0` because:
- `len()` is never negative
- one less character
- conveys more the meaning of your test, inequality is usually a bit harder to understand

2021-06-11 16:32 UTC, xpetit commented
I get an error when I run the tests :
```
~/x/zone01/go-tests/tests $ for d in *_test; do echo $d; go run ./$d; done
[...]
# github.com/01-edu/go-tests/tests/listforeachif_test
listforeachif_test/main.go:72:45: undefined: piscine.IsAl_node
[...]
```

2021-06-11 17:19 UTC, LEEDASILVA commented on solutions/challenge.go
> +func ChallengeList(f string, l, l1 *List, data []interface{}, args ...interface{}) {
you are right the names are not so good, correcting it now

2021-06-11 17:20 UTC, LEEDASILVA commented on solutions/challenge.go
> +func CopyList(listStu *List) *List {
it is used in other packages

2021-06-11 17:23 UTC, LEEDASILVA commented on solutions/challenge.go
>  	for it != nil {
yes yes it will way better thank you

2021-06-11 17:33 UTC, LEEDASILVA commented on solutions/challenge.go
> +	} else {
omg yes you are right, concentrating on other stuff and did not see that one, thanks

2021-06-11 17:35 UTC, LEEDASILVA commented on solutions/challenge.go
>  	RandLen := random.IntBetween(0, len(t))
this functions is being exported

2021-06-11 17:42 UTC, LEEDASILVA commented on solutions/challenge.go
> +func ListPushNode(l *NodeI, data int) *NodeI {
did not see that one thank you

2021-06-11 21:35 UTC, LEEDASILVA commented on solutions/challenge.go
> +func IntToStringface(t []string) []interface{} {
kind of, it was also to convert a slice of strings to a slice of interface

2021-06-11 23:50 UTC, LEEDASILVA commented on solutions/listforeachif.go
> +func IsAl_node(node *NodeL) bool {
fixed

2021-06-18 13:48 UTC, xpetit requested changes

2021-06-18 13:48 UTC, xpetit commented on solutions/challenge.go
> +	iterator := l
https://github.com/01-edu/go-tests/pull/4#discussion_r650084374

2021-06-18 13:48 UTC, xpetit commented on solutions/challenge.go
> +	iterator := l
Also I'm not sure what happen if `l` is `nil`...
It appears both `n` and `n.Next` will have `data` isn't it ?
(multiple occurrences)

2021-06-18 13:48 UTC, xpetit commented on solutions/challenge.go
> +	}
https://github.com/01-edu/go-tests/pull/4#discussion_r650079740

2021-06-18 13:48 UTC, xpetit commented on tests/listfind_test/main.go
> +		link1 = &solutions.List{}
Here you want to put it at the beginning of the loop, and remove the declaration outside of the loop.
(multiple occurrences)

2021-06-18 13:48 UTC, xpetit commented on tests/sortedlistmerge_test/main.go
> +	head := l
https://github.com/01-edu/go-tests/pull/4#discussion_r650084374
You can use `l` directly

2021-06-18 15:05 UTC, LEEDASILVA commented on solutions/challenge.go
> +	}
:+1:

2021-06-18 16:08 UTC, LEEDASILVA commented on tests/sortedlistmerge_test/main.go
> +	head := l
actually this function is not needed, thank you

2021-06-18 16:17 UTC, xpetit approved these changes

2021-06-18 16:17 UTC, merged