Solution and Test Devisors
01-edu/go-tests pull request #40
Opened 2022-06-14 08:48 UTC by zainabdnaya

2022-06-14 10:30 UTC, Hamzaelkhatri approved these changes

2022-06-21 01:27 UTC, davidrobert99 requested changes

2022-06-21 01:27 UTC, davidrobert99 commented on solutions/devisors.go
> +}
This file shouldn't be named divisors.go?

2022-06-21 23:26 UTC, davidrobert99 approved these changes

2022-06-22 15:17 UTC, merged