test(cameltosnakecase):add test & solutions
01-edu/go-tests pull request #41
Opened 2022-06-14 10:05 UTC by Hamzaelkhatri

2022-06-14 13:29 UTC, zainabdnaya commented on solutions/cameltosnakecase.go
> +		if s[i] >= 'A' && s[i] <= 'Z' {
The code gives the result different then the subject :
   CamelToSnakeCase("HelloWorld") => _Hello_World
I think u should skip the first character

2022-06-14 13:34 UTC, Hamzaelkhatri commented on solutions/cameltosnakecase.go
> +		if s[i] >= 'A' && s[i] <= 'Z' {
fixed

2022-06-14 13:58 UTC, zainabdnaya approved these changes
All Good

2022-06-23 10:18 UTC, MSilva95 requested changes
Fix the solution and test accordingly to the comments on the readme for this exercise

2022-06-23 10:59 UTC, Hamzaelkhatri commented
@MSilva95 which comments?

2022-06-23 13:40 UTC, MSilva95 reviewed
the one in the subject for this exercise.
https://github.com/01-edu/public/pull/1221

2022-08-04 18:00 UTC, MSilva95 commented on tests/cameltosnakecase/main.go
> +	years := []string{
add tests to cover this:

- The word does not end on a capitalized letter: (CamelCasE).
- No two capitalized letters shall follow directly each other (CamelCAse).
- Numbers or punctuation are not allowed in the word anywhere (camelCase1).

2022-08-04 18:01 UTC, MSilva95 requested changes
add the new test cases and make the solution follow the rules if necessary!

2022-08-05 19:32 UTC, Hamzaelkhatri commented on tests/cameltosnakecase/main.go
> +	years := []string{
fixed

2022-11-08 17:11 UTC, jotapero approved these changes
Looks Good :alien:

2022-11-10 12:26 UTC, tiagocollot requested changes

2022-11-10 12:26 UTC, tiagocollot commented on solutions/cameltosnakecase.go
> +func containOnlyAlphabe(str string) bool {
The code seems to be working fine. I would suggest to correct the function name: "containOnlyAlphabet"

2022-11-10 12:26 UTC, tiagocollot commented on solutions/cameltosnakecase.go
> +	if len(s) == 0 || !containOnlyAlphabe(s) {
Same as above, fix function name typo.

2022-11-10 14:15 UTC, jotapero commented on solutions/cameltosnakecase.go
> +	if len(s) == 0 || !containOnlyAlphabe(s) {
fixed

2022-11-10 18:07 UTC, tiagocollot approved these changes
LGTM! ⚡

2022-12-05 12:21 UTC, merged