test(paramrange):add test & solution
01-edu/go-tests pull request #42
Opened 2022-06-14 11:56 UTC by Hamzaelkhatri

2022-06-14 13:23 UTC, zainabdnaya approved these changes
All Good

2022-06-22 10:27 UTC, davidrobert99 requested changes

2022-06-22 10:27 UTC, davidrobert99 commented on tests/paramrange_test/main.go
> +		{"Hello world"},
There is no test case where the minimum value is not in the first position. If the student doesn't update the min value correctly, the tests pass.

for example, if we replace on the solution
```go
if i < min {
	min = i
}
```

with 

```go
if i < min {
	max = i
}
```

the test passes.

2022-06-22 11:00 UTC, davidrobert99 approved these changes

2022-06-22 15:16 UTC, merged