CountStars solution and test
01-edu/go-tests pull request #43
Opened 2022-06-14 14:23 UTC by zainabdnaya

2022-06-15 10:51 UTC, davidrobert99 requested changes

2022-06-15 10:51 UTC, davidrobert99 commented on solutions/countstars.go
> +}
This solution does not respect the content of the exercise.

fmt.Println(CountStars(5)) -> "1 star...2 star...3 star...4 star...5 star...".

2022-06-30 15:25 UTC, MSilva95 requested changes

2022-06-30 15:25 UTC, MSilva95 commented on solutions/countstars.go
> +}
Please format your code

2022-06-30 15:25 UTC, MSilva95 commented on solutions/countstars.go
> +			res = res + strconv.Itoa(i) + stars
is it possible to do it without strconv.Itoa?
If not we must specify it to allow this function!

2022-06-30 15:25 UTC, MSilva95 commented on tests/countstars/main.go
> +	table := []int{1, 2, 9, -258, 0, 48, 94, 41,-56}
add more tests here and one or two larger numbes under 1000

2022-06-30 20:14 UTC, zainabdnaya commented on solutions/countstars.go
> +			res = res + strconv.Itoa(i) + stars
Okay, I will add it in the Subject that is Allowed to use it

2022-06-30 20:59 UTC, zainabdnaya commented on solutions/countstars.go
> +}
Done

2022-06-30 20:59 UTC, zainabdnaya commented on tests/countstars/main.go
> +	table := []int{1, 2, 9, -258, 0, 48, 94, 41,-56}
Done

2022-07-14 09:22 UTC, MSilva95 commented on solutions/countstars.go
> +			res = res + strconv.Itoa(i) + stars
You can leave the solution like it is, but it is possible to do it without the use of strconv, that was what i wanted to know.

2022-07-14 16:29 UTC, MSilva95 approved these changes

2022-08-04 11:01 UTC, merged