test(sumArray): add test & solution
01-edu/go-tests pull request #44
Opened 2022-06-14 15:06 UTC by Hamzaelkhatri

2022-06-14 23:13 UTC, zainabdnaya commented on tests/sumarray_test/main.go
> +		{-1, -2, -3, -4, -5, -6, -7, -8, -9, -10},
I think u can add the INT_MAX or INT_MIN "it's optional "

2022-06-14 23:13 UTC, zainabdnaya approved these changes
Test it the code works well

2022-06-15 12:04 UTC, davidrobert99 requested changes

2022-06-15 12:04 UTC, davidrobert99 commented on solutions/sumarray.go
> +}
The name of the function does not match the one on the public. Here it is SumArray and on the public repo is ArraySum.

2022-06-21 00:30 UTC, davidrobert99 approved these changes

2022-06-22 15:16 UTC, merged