vowls-index solution and test
01-edu/go-tests pull request #45
Opened 2022-06-15 11:55 UTC by zainabdnaya

2022-06-21 02:18 UTC, davidrobert99 commented on tests/tolower_test/main.go
> -}
Why was this deleted?

2022-06-21 02:18 UTC, davidrobert99 commented on tests/vowelsindex_test/main.go
> +
Probably add more test cases like for example "AAEO$%&UOTX" or "*+-aeiouAEMNOoa"

2022-07-13 12:56 UTC, Hamzaelkhatri approved these changes
LGTM , just fix format of `solutions/vowelsindex.go`

2022-07-13 13:11 UTC, zainabdnaya commented on solutions/vowelsindex.go
> +
done

2022-07-14 16:56 UTC, MSilva95 requested changes

2022-07-14 16:56 UTC, MSilva95 commented on tests/vowelsindex_test/main.go
> +	table := []string{"student", "hello Iyan", "world", "Hello! How are you?", "AAEO$%&UOTX", "AEMNOoa*+-aeiou", "wo5opi=ws8;eza"}
add tests that don't have vowels and empty tests

2022-07-15 14:02 UTC, MSilva95 commented on tests/vowelsindex_test/main.go
> +	table := []string{"student", "hello Iyan", "world", "Hello! How are you?", "AAEO$%&UOTX", "AEMNOoa*+-aeiou", "wo5opi=ws8;eza"}
Add the test 

{"ptghjkvl"}

2022-07-15 14:42 UTC, MSilva95 approved these changes

2022-08-04 10:30 UTC, merged