test(swapName):add solution & test
01-edu/go-tests pull request #46
Opened 2022-06-15 12:26 UTC by Hamzaelkhatri

2022-06-15 18:47 UTC, zainabdnaya approved these changes
All Good

2022-06-22 14:57 UTC, davidrobert99 reviewed
It is a good idea to improve the code. There are a lot of "for" cycles.

2022-06-28 10:39 UTC, MSilva95 reviewed
If You cant create a solution without the functions mentioned in the comments, we need to recheck if this exercise will be in the exams or not

2022-06-28 10:39 UTC, MSilva95 commented on tests/swapname_test/main.go
> +		{"Hello World"},
Same here in the tests, we should use names as well

2022-06-28 10:39 UTC, MSilva95 commented on solutions/swapname/main.go
> +package main
Try to create a solution not using (make) and (strings.TrimSpace) so that we can restrict this functions.

2022-06-28 19:43 UTC, Hamzaelkhatri commented on solutions/swapname/main.go
> +package main
i changed , ty

2022-07-12 17:11 UTC, MSilva95 requested changes

2022-07-12 21:28 UTC, Hamzaelkhatri commented on solutions/swapname/main.go
> +			fmt.Println("[" + fullName[1] + " " + fullName[0] + "]")
fixed

2022-07-26 16:34 UTC, MSilva95 requested changes
add one valid test with extra spaces in the middle of the arg

2022-08-02 12:04 UTC, MSilva95 approved these changes

2022-08-02 19:15 UTC, merged