test & slution numofdigits
01-edu/go-tests pull request #47
Opened 2022-06-15 18:23 UTC by zainabdnaya

2022-06-15 18:44 UTC, Hamzaelkhatri approved these changes

2022-06-30 14:45 UTC, MSilva95 requested changes

2022-06-30 14:45 UTC, MSilva95 commented on tests/numofdigits_test/main.go
> +		1,
add the test for {0} and some more negatives

2022-07-03 11:44 UTC, zainabdnaya commented on tests/numofdigits_test/main.go
> +		1,
dine

2022-07-14 15:34 UTC, MSilva95 approved these changes

2022-08-04 11:02 UTC, merged