test(IsTheSqaureAchild):add test & solution
01-edu/go-tests pull request #49
Opened 2022-06-16 11:10 UTC by Hamzaelkhatri

2022-06-17 17:19 UTC, zainabdnaya approved these changes
All Good

2022-06-17 17:28 UTC, Hamzaelkhatri commented on solutions/isthesquareachild.go
> +	return number*number == square
i change the way of return , in the issue @mohamedLazyBob  say `(9, 3) => true`
n1 * n1 == n2 or n2 * n2 == n1 . but i use just the first case , to make the execices more easier

2022-07-05 14:10 UTC, MSilva95 requested changes

2022-07-05 14:10 UTC, MSilva95 commented on tests/isthesquareachild_test/main.go
> +		{1, 1},
add the case that @zainabdnaya asked in the readme file ...

2022-07-05 20:06 UTC, zainabdnaya approved these changes
LGTM

2022-07-08 09:17 UTC, MSilva95 requested changes

2022-07-08 09:17 UTC, MSilva95 commented on solutions/issquare.go
> +func isSquare(number int, square int) bool {
function name is wrong...
Needs to be upercase.
IsSquare()

2022-07-08 09:24 UTC, Hamzaelkhatri commented on solutions/issquare.go
> +func isSquare(number int, square int) bool {
fixed

2022-07-26 15:31 UTC, MSilva95 requested changes

2022-07-26 15:31 UTC, MSilva95 commented on tests/issquare_test/main.go
> +func main() {
add more tests, i can pass this with a wrong solution like so.
```
func IsSquare(number int, square int) bool {
	return number*number == square
}
```

2022-07-26 15:41 UTC, Hamzaelkhatri commented on tests/issquare_test/main.go
> +func main() {
fixed

2022-07-27 16:27 UTC, MSilva95 approved these changes

2022-08-02 19:14 UTC, merged