Tests improvement1
01-edu/go-tests pull request #5
Opened 2021-06-14 13:31 UTC by Frenchris

improved test for:
1) rot14 (added some extra singular cases)
2) wdmatch (added the example of the readme as a first test)

2021-06-14 14:04 UTC, xpetit requested changes

2021-06-14 14:04 UTC, xpetit commented on tests/rot14_test/main.go
> +
`table` is a variable containing examples so you don't have to create a variable named `example` and add it to `table`. You can directly append to the table your data, or even better, declaring it during initialization

2021-06-18 15:36 UTC, Frenchris commented on tests/rot14_test/main.go
> +
I just added it during initialization.

2021-06-18 16:27 UTC, xpetit approved these changes

2021-06-18 16:27 UTC, merged