Add Test & Solution Concat_args
01-edu/go-tests pull request #53
Opened 2022-06-16 21:48 UTC by zainabdnaya

2022-06-16 21:56 UTC, Hamzaelkhatri requested changes

2022-06-16 21:56 UTC, Hamzaelkhatri commented on tests/concat2args_test/main.go
> +	args := [][]string{
add empty args

2022-06-16 21:56 UTC, Hamzaelkhatri commented on tests/concat2args_test/main.go
> +		{"1 + ", "9 = 10"},
add more than 3 args too

2022-06-17 17:36 UTC, Hamzaelkhatri approved these changes
LGTM!

2022-07-08 11:05 UTC, MSilva95 requested changes

2022-07-08 11:05 UTC, MSilva95 commented on tests/concat2args_test/main.go
> +		{"1 + ", "9 = 10"},
add This as well:
```
{""},
{},
```

2022-07-08 23:46 UTC, zainabdnaya commented on tests/concat2args_test/main.go
> +		{"1 + ", "9 = 10"},
Done

2022-08-04 17:32 UTC, MSilva95 approved these changes

2022-08-04 22:35 UTC, merged