Test & Solution argsort
01-edu/go-tests pull request #55
Opened 2022-06-18 11:41 UTC by zainabdnaya

2022-06-18 15:26 UTC, Hamzaelkhatri requested changes

2022-06-18 15:26 UTC, Hamzaelkhatri commented on solutions/argsort/main.go
> +	z01.PrintRune('\n')
in the subject, you say that the program should print nothing if   `the number of arguments is not `1` Print nothing`. but here the program can print `\n` in any case

2022-06-21 12:08 UTC, zainabdnaya commented on solutions/argsort/main.go
> +	z01.PrintRune('\n')
I changed the subject

2022-06-21 12:43 UTC, Hamzaelkhatri commented on tests/argsort_test/main.go
> +		{"125", "wde", "abc"},
add empty string 
```
{""}
{}

2022-06-23 18:33 UTC, Hamzaelkhatri approved these changes

2022-06-28 20:20 UTC, Hamzaelkhatri approved these changes

2022-07-26 14:19 UTC, MSilva95 requested changes

2022-07-26 14:19 UTC, MSilva95 commented on tests/argsort_test/main.go
> +		{"def"},
add more tests, with other printable characters, and with spaces at the end and middle of the string

2022-07-26 16:19 UTC, zainabdnaya commented on tests/argsort_test/main.go
> +		{"def"},
Done

2022-08-02 10:07 UTC, MSilva95 submitted a review, later dismissed

2022-08-02 10:07 UTC, MSilva95 commented on tests/argsort_test/main.go
> +		{"  @\!\\n"},
did you try to run the test locally?
Was it possible? i cant run it with this slashes...

2022-08-02 10:07 UTC, MSilva95 commented on tests/argsort_test/main.go
> +		{"9^_\`abc"},
same here...

2022-08-04 10:15 UTC, MSilva95 reviewed
My comments have not been answered and no changes have been made, why is this here to review again?

2022-08-04 10:19 UTC, zainabdnaya commented
> My comments have not been answered and no changes have been made, why is this here to review again?

I did but I didn't submit it  
it fixed now

2022-08-04 10:34 UTC, MSilva95 commented on tests/argsort_test/main.go
> +		{"9^_\`abc"},
if i try to run it like it is it gives me an error 
![test](https://user-images.githubusercontent.com/53977751/182826386-ba7437e2-2b58-4da9-bb64-8e11c8286945.png)
Yours works fine?

2022-08-04 10:35 UTC, MSilva95 commented on tests/argsort_test/main.go
> +		{"9^_\`abc"},
mine only works if i set the tests like so :
```
{"  @\\!\\n"},
{"9^_\\`abc"},
```

2022-08-04 10:49 UTC, zainabdnaya commented on tests/argsort_test/main.go
> +		{"9^_\`abc"},
You're right. I had a problem with commits; it didn't show this problem, but after I fixed it, it showed the same msg.

2022-11-08 16:37 UTC, jotapero approved these changes
Looks Good :alien:

2022-11-10 13:52 UTC, tiagocollot approved these changes
LGTM! ⚡

2022-12-05 12:18 UTC, merged