buzzinga-test
01-edu/go-tests pull request #60
Opened 2022-06-20 21:30 UTC by zainabdnaya

2022-06-20 22:49 UTC, Hamzaelkhatri approved these changes

2022-07-18 16:58 UTC, MSilva95 requested changes

2022-07-18 16:58 UTC, MSilva95 commented on solutions/buzzinga.go
> +		fmt.Print("*")
missing newline for negatives

2022-07-19 00:17 UTC, zainabdnaya commented on tests/buzzinga_test/main.go
> +	challenge.Function("BuzZinga", student.BuzZinga, solutions.BuzZinga, 20)
corrected

2022-07-19 00:17 UTC, zainabdnaya commented on solutions/buzzinga.go
> +		fmt.Print("*")
corrected

2022-07-22 16:19 UTC, MSilva95 requested changes

2022-07-22 16:19 UTC, MSilva95 commented on tests/buzzinga_test/main.go
> +package main
Try to run the test, its not working...
You should define the int32 and use an array to keep it clean...
something like this
```
func main() {
	args := []int32{20, 15, -125, 10, 5, 4, -9, 9, 24, 0, -85, 06, 11}

	for _, arg := range args {
		challenge.Function("BuzZinga", student.BuzZinga, solutions.BuzZinga, arg)
	}
}
```

2022-07-26 14:05 UTC, MSilva95 approved these changes

2022-08-04 09:28 UTC, merged