add test & solution of Unzipstring
01-edu/go-tests pull request #62
Opened 2022-06-21 20:42 UTC by zainabdnaya

2022-06-21 20:47 UTC, Hamzaelkhatri commented on solutions/unzipstring.go
> +    var result string
add condition to check if the string is empty , also check if len of argument is less than 2 
``` go 
	if len(str) == 0 || len(str) < 2 {
		return "Invalid output"
	}
```

2022-06-21 20:55 UTC, zainabdnaya commented on tests/unzipstring_test/main.go
> +	arr := []string{"6H8a", "3p6i1W", "2O5u2H0e", "2d", "2a 6p8f", "2p4;7g", "2t4dD", "82t4D", "2k5%9.", "", "5w6	2t",}
number + whatever but not number

2022-06-28 20:14 UTC, Hamzaelkhatri approved these changes
LGTM!

2022-07-18 15:31 UTC, MSilva95 requested changes

2022-07-18 15:31 UTC, MSilva95 commented on tests/unzipstring_test/main.go
> +	arr := []string{
add some more test because the ones you have are the ones in the readme, its easy to cheat this way.

2022-07-27 16:43 UTC, MSilva95 approved these changes

2022-08-04 09:25 UTC, merged