Ping pong
01-edu/go-tests pull request #63
Opened 2022-06-22 13:01 UTC by eslopfer

Solution and test for pingpong subject

2022-06-22 18:54 UTC, Hamzaelkhatri requested changes

2022-06-23 09:04 UTC, eslopfer commented on solutions/pingpong/main.go
> +}
Thanks, I'll add it.

2022-06-23 09:05 UTC, eslopfer commented on tests/pingpong_test/main.go
> +		{"100"},
Thanks for the feedback. Wouldn't this be one of the 'improbable' test cases since in the description we are telling the student that the numbers will be from 0 to 100?

2022-06-24 09:13 UTC, Hamzaelkhatri approved these changes

2022-06-30 17:34 UTC, MSilva95 approved these changes

2022-07-14 07:34 UTC, merged