test(addfront):add test & solution
01-edu/go-tests pull request #68
Opened 2022-06-24 20:24 UTC by Hamzaelkhatri

2022-06-27 11:54 UTC, eslopfer commented on tests/addfront_test/main.go
> +	for _, arg := range table {
When I run this test I get the following error:
```console
tests/addfront_test/main.go:20:83: too many arguments in call to challenge.Function
        have (string, func(str string, slice []string) []string, func(str string, slice []string) []string, string, []string)
        want (string, interface{}, interface{}, ...interface{})
  ```

2022-06-28 11:43 UTC, MSilva95 requested changes

2022-06-28 11:43 UTC, MSilva95 commented on tests/addfront_test/main.go
> +		{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"},
add random test
```
		{random.Str(chars.Words, 6), "Hello", ""},

2022-06-28 11:43 UTC, MSilva95 commented on solutions/addfront.go
> +package solutions
Don't forget to fix your solution to implement the changes requested in the readme.

2022-06-28 20:34 UTC, Hamzaelkhatri commented on solutions/addfront.go
> +package solutions
i added

2022-07-08 13:42 UTC, MSilva95 requested changes

2022-07-08 18:14 UTC, Hamzaelkhatri commented on solutions/addfront.go
> +func AddFront(str string, slice []string) []string {
the function `fmt.Println` print space after each element of the array expect the last one, so in this case `[]string{"", "a", "b", "c"}`  **Println** print space  after the (empty) element . 
if we use, for example : 
```go 
result := AddFront("Hello", []string{"", "a", "b", "c"})
for _, str := range result {
       fmt.Println("[" + str + "]")
}
```
and the output 
```console 
$ go run  . 
[Hello]
[]
[a]
[b]
[c]
```
The solution's output adds two spaces between Hello and a.

2022-07-26 16:14 UTC, MSilva95 approved these changes

2022-08-02 19:16 UTC, merged