1268 sum 1
01-edu/go-tests pull request #70
Opened 2022-06-29 10:04 UTC by eslopfer

Add tests and solution for sum subject

2022-06-29 10:22 UTC, Hamzaelkhatri requested changes

2022-06-29 10:22 UTC, Hamzaelkhatri commented on solutions/sum.go
> +func Sum(a, b string) int {
`fmt.Println(Sum("A", "1")) ===> 1` should work like that ?

2022-06-29 10:59 UTC, eslopfer commented on solutions/sum.go
> +func Sum(a, b string) int {
Given that we are telling the student that the function arguments will be single `digits`, wouldn't this be an unrealistic scenario?

2022-06-29 11:11 UTC, Hamzaelkhatri commented on solutions/sum.go
> +func Sum(a, b string) int {
actually, the subject says `arguments will be single digits` so that is why we should manage this case. 
if we set as argument anything else digit should return `0`

2022-06-29 11:26 UTC, eslopfer commented on solutions/sum.go
> +func Sum(a, b string) int {
Exactly, if the arguments will be single digits, there is no need to test for cases that are never going to happen, right?. Thanks for pointing this out, maybe the readme is not clear enough. I will rephrase the readme to make it clear that what it meant was to check for digits that are not single to avoid future confusions.

2022-06-30 15:26 UTC, Hamzaelkhatri approved these changes

2022-06-30 15:53 UTC, MSilva95 commented on solutions/sum.go
> +	numA, _ := strconv.Atoi(a)
Is it possible without the strconv.Atoi()?

2022-07-05 14:26 UTC, MSilva95 approved these changes

2022-07-14 07:33 UTC, merged