1271 concatenate test
01-edu/go-tests pull request #71
Opened 2022-06-29 10:54 UTC by eslopfer

Write tests and solution for concatenate subject

2022-06-30 15:39 UTC, Hamzaelkhatri approved these changes

2022-06-30 16:18 UTC, MSilva95 requested changes

2022-06-30 16:18 UTC, MSilva95 commented on tests/concatenate_test/main.go
> +		{},
add test fort this case:

go run . "hello there" "how are you?"
go run . "hello there" " "

2022-07-05 14:25 UTC, MSilva95 approved these changes

2022-07-14 07:33 UTC, merged