1273 printevenarguments 1
01-edu/go-tests pull request #72
Opened 2022-06-29 12:03 UTC by eslopfer

Add tests and solution for printevenarguments subject.

2022-06-30 15:33 UTC, Hamzaelkhatri approved these changes

2022-07-08 10:39 UTC, MSilva95 requested changes

2022-07-08 10:39 UTC, MSilva95 commented on tests/printevenarguments_test/main.go
> +	table := [][]string{
Add a test to cover this case
```
$ go run . a | cat -e
```

2022-07-08 10:39 UTC, MSilva95 commented on solutions/printevenarguments/main.go
> +package main
Change the solution if necessary to cover the case i said in the readme

2022-07-11 17:53 UTC, eslopfer commented on tests/printevenarguments_test/main.go
> +	table := [][]string{
Thanks I'll do that.

2022-07-11 17:53 UTC, eslopfer commented on solutions/printevenarguments/main.go
> +package main
Done. Thank you.

2022-07-12 17:21 UTC, MSilva95 approved these changes

2022-07-14 07:30 UTC, merged