add test & solution
01-edu/go-tests pull request #76
Opened 2022-07-07 18:08 UTC by Hamzaelkhatri

2022-07-13 23:16 UTC, zainabdnaya approved these changes
lgtm

2022-07-18 15:56 UTC, MSilva95 requested changes
Fix this commits and then i will test it

2022-08-02 11:46 UTC, MSilva95 requested changes

2022-08-02 11:46 UTC, MSilva95 commented on tests/reversestrings_test/main.go
> +package main
format the code and its good to go...

2022-08-02 15:31 UTC, Hamzaelkhatri commented on tests/reversestrings_test/main.go
> +package main
fixed

2022-08-04 10:06 UTC, MSilva95 approved these changes

2022-08-04 22:38 UTC, merged