1270 multorsum 1
01-edu/go-tests pull request #77
Opened 2022-07-08 09:33 UTC by eslopfer

Add test and solution for multorsum subject

2022-07-08 10:10 UTC, Hamzaelkhatri requested changes

2022-07-08 10:10 UTC, Hamzaelkhatri commented on solutions/multorsum.go
> +func MultOrSum(ints []int, init int) int {
Add the condition if the slice is empty as the subject says.

2022-07-12 23:27 UTC, Hamzaelkhatri approved these changes

2022-11-09 17:25 UTC, tiagocollot approved these changes
LGTM ⚡

2022-12-05 12:22 UTC, merged