solution of weareuniaue
01-edu/go-tests pull request #82
Opened 2022-07-18 11:36 UTC by zainabdnaya

2022-07-18 12:46 UTC, Hamzaelkhatri requested changes

2022-07-18 12:46 UTC, Hamzaelkhatri commented on solutions/weareunique.go
> +
remove this empty line

2022-07-19 23:02 UTC, zainabdnaya commented on solutions/weareunique.go
> +
done

2022-07-21 11:02 UTC, Hamzaelkhatri requested changes

2022-07-21 11:02 UTC, Hamzaelkhatri commented on tests/unzipstring_test/main.go
> +		challenge.Function("Unzipstring", student.Unzipstring, solutions.Unzipstring, s)
u need to add two params here , `str1,str2`

2022-07-21 20:42 UTC, zainabdnaya commented on tests/unzipstring_test/main.go
> +		challenge.Function("Unzipstring", student.Unzipstring, solutions.Unzipstring, s)
done

2022-07-21 22:18 UTC, Hamzaelkhatri approved these changes
LGTM!

2022-07-22 13:31 UTC, MSilva95 requested changes

2022-07-22 13:31 UTC, MSilva95 commented on solutions/weareunique.go
> +package solutions
its not returning -1 when it should.
How did this get here with a wrong solution? Was it not tested?

2022-07-22 13:55 UTC, zainabdnaya commented on solutions/weareunique.go
> +package solutions
The subject is wrong because I meant to write that I should return ` 0` if there are no unique characters.

2022-07-22 15:05 UTC, MSilva95 requested changes

2022-07-22 15:05 UTC, MSilva95 commented on solutions/weareunique.go
> +package solutions
not fixed, now it returns 0 where it should return -1
Test it first before you send it to review, don't feel like you have to do this in a hurry...

2022-07-22 15:15 UTC, zainabdnaya commented on solutions/weareunique.go
> +package solutions
Yes, You are right I didn't push the change , My bad sorry

2022-07-26 15:00 UTC, MSilva95 requested changes

2022-07-26 15:00 UTC, MSilva95 commented on tests/weareunique_test/main.go
> +		{"foo", "boo"},
You are repeating a lot of tests... Why?

2022-07-26 15:41 UTC, zainabdnaya commented on tests/weareunique_test/main.go
> +		{"foo", "boo"},
corrected

2022-08-02 10:12 UTC, MSilva95 commented on tests/weareunique_test/main.go
> +		{"foo", "boo"},
there is still repetition i the test...

2022-08-03 00:41 UTC, zainabdnaya commented on tests/weareunique_test/main.go
> +		{"foo", "boo"},
fixed

2022-08-04 10:25 UTC, MSilva95 commented on tests/weareunique_test/main.go
> +		{"foo", "boo"},
is it?
I can still see one more repetition on the test...
The test case {"", ""} is there twice...
This is one of the points @davhojt covered in the presentation about the reviews. please be more careful with this as there is no need for me to review this 3 times just to check if all the repetition is gone or not.

2022-08-04 10:30 UTC, zainabdnaya commented on tests/weareunique_test/main.go
> +		{"foo", "boo"},
all the repetition is gone Now

2022-11-08 16:53 UTC, jotapero approved these changes
Looks Good :alien:

2022-11-10 12:55 UTC, tiagocollot approved these changes

2022-11-10 18:17 UTC, tiagocollot approved these changes
LGTM ⚡

2022-12-05 12:20 UTC, merged