DEV-3177-new-go-exercise-fromto
01-edu/go-tests pull request #83
Opened 2022-07-27 18:49 UTC by Hamzaelkhatri

2022-08-08 14:30 UTC, tiagocollot requested changes

2022-08-08 14:30 UTC, tiagocollot commented on tests/swapname_test/main.go
> +	"github.com/01-edu/go-tests/lib/challenge"
Since is only taking one import can be "import............." instead of "import (.......................................) "

2022-08-08 15:57 UTC, tiagocollot requested changes

2022-08-08 15:57 UTC, tiagocollot commented on solutions/fromto.go
> +import (
Since is only importing one package theres is no need of "(......) around "strconv"

2022-08-08 16:01 UTC, Hamzaelkhatri commented on solutions/fromto.go
> +import (
fixed

2022-08-08 16:13 UTC, tiagocollot approved these changes

2022-11-02 15:31 UTC, jotapero approved these changes

2022-11-14 07:04 UTC, eslopfer approved these changes
LGTM! :rocket:

2023-06-19 16:29 UTC, merged