DEV-3176-new-go-exercise-reversesecondhalf
01-edu/go-tests pull request #86
Opened 2022-07-28 12:12 UTC by zainabdnaya

2022-08-04 15:34 UTC, tiagocollot requested changes

2022-08-04 15:34 UTC, tiagocollot commented on tests/reversesecondhalf/main.go
> +	table := []string{"hello wold", "", "Kimetsu no Yaiba", "Z", "email123@live.fr", "write  ==> 45m$", "-552", "w58tw7474abc", "fifa world cup `2022`",}
Found an extra space in this string "write  ==> 45m$" the extra space is in between "write" and the "==>".

2022-08-04 22:32 UTC, zainabdnaya commented on tests/reversesecondhalf/main.go
> +	table := []string{"hello wold", "", "Kimetsu no Yaiba", "Z", "email123@live.fr", "write  ==> 45m$", "-552", "w58tw7474abc", "fifa world cup `2022`",}
This is a test case, So it could be anything since the extra space doesn't make any problem.

2022-08-08 08:07 UTC, tiagocollot approved these changes

2022-11-02 11:03 UTC, tiagocollot approved these changes

2022-11-14 06:51 UTC, eslopfer requested changes
Review pending until instructions are clear.

2022-12-05 11:14 UTC, jotapero approved these changes
LGMT :alien:

2022-12-05 11:15 UTC, merged