DEV-3202-new-go-exercicse-be-zero
01-edu/go-tests pull request #87
Opened 2022-07-28 17:24 UTC by Hamzaelkhatri

2022-08-04 13:11 UTC, tiagocollot requested changes

2022-08-04 13:14 UTC, Hamzaelkhatri commented on tests/bezero_test/main.go
> +		{},
Yes, it's part of the syntax.

2022-08-04 15:11 UTC, tiagocollot approved these changes

2022-11-03 16:27 UTC, jotapero requested changes
Looks Good just needs to remove unnecessary files :alien:

2022-11-08 16:49 UTC, closed without merging