DEV-3181-new-go-exercise-printandmiss
01-edu/go-tests pull request #96
Opened 2022-07-30 01:55 UTC by zainabdnaya

2022-08-11 16:09 UTC, Hamzaelkhatri requested changes

2022-08-11 16:09 UTC, Hamzaelkhatri commented on solutions/printandmiss.go
> +func PrintAndMiss(arg string, loop int) string {
Change name `loop` to, for example `, num`. It is confusing.

2022-08-11 16:09 UTC, Hamzaelkhatri commented on solutions/printandmiss.go
> +	var _str strings.Builder
you don't have to use `strings` library just use `str:=""`

2022-08-11 16:52 UTC, zainabdnaya commented on solutions/printandmiss.go
> +func PrintAndMiss(arg string, loop int) string {
it's fixed

2022-08-11 16:52 UTC, zainabdnaya commented on solutions/printandmiss.go
> +	var _str strings.Builder
it's fixed

2022-08-14 18:39 UTC, Hamzaelkhatri approved these changes

2022-11-02 16:44 UTC, jotapero requested changes

2022-11-02 16:44 UTC, jotapero commented on solutions/printandmiss.go
> +	if arg == "" || num < 0 {
This condition needs to be fixed. Returns "Invalid Output" for negative numbers and it should return newline

2022-11-08 11:58 UTC, tiagocollot commented on solutions/printandmiss.go
> +	if arg == "" || num < 0 {
It was an instructional error, as written in the subject file. It is now fixed.

2022-11-09 14:36 UTC, jotapero approved these changes
LGTM :alien:

2022-11-14 07:29 UTC, eslopfer requested changes
This review is pending until the subject is fixed.

2023-06-20 15:14 UTC, merged