DEV-3175-new-go-exercise-printfirsthalf
01-edu/go-tests pull request #98
Opened 2022-07-30 02:42 UTC by zainabdnaya

2022-08-04 15:30 UTC, jotapero requested changes

2022-08-04 15:30 UTC, jotapero commented on solutions/printfirsthalf.go
> +func Printfirsthalf(str string) string {
change to "PrintFirstHalf" - maintain PascalCase formatting

2022-08-04 15:30 UTC, jotapero commented on tests/printfirsthalf_test/main.go
> +		challenge.Function("Printfirsthalf", student.Printfirsthalf, solutions.Printfirsthalf, s)
Same here with case formatting "PrintFirstHalf

2022-08-04 21:35 UTC, zainabdnaya commented on solutions/printfirsthalf.go
> +func Printfirsthalf(str string) string {
it's fixed

2022-08-04 21:35 UTC, zainabdnaya commented on tests/printfirsthalf_test/main.go
> +		challenge.Function("Printfirsthalf", student.Printfirsthalf, solutions.Printfirsthalf, s)
it's fixed

2022-08-09 08:33 UTC, jotapero approved these changes

2022-10-20 13:05 UTC, closed without merging